### ISSUE TITLE
Aggiunta di publiccode.yml

### ISSUE THREAD

**Issue by libremente** [INRIM/inrim-forms-demo#7]
Buongiorno @archetipo, credo che questo tool possa essere molto apprezzato nel catalogo. Sarebbe possibile aggiungere un file publiccode.yml nella root per indicizzarlo?

Se serve supporto resto a disposizione.
Grazie e buon lavoro

**Comment by archetipo** [comment]
Buongiorno @libremente , 

   grazie dell'attenzione e della segnalazione
   Ho provveduto ad aggiungere il publiccode.yml al progetto.
  Grazie della disponibilità
Buon lavoro
Ciao

**Comment by libremente** [comment]
Grazie molte @archetipo! Chiudo
